//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AltusTest.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AltusTest.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid binary count number. Please be sure you use a number between 0 and 100..
        /// </summary>
        public static string app_BinaryCountException {
            get {
                return ResourceManager.GetString("app_BinaryCountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number between 0 and 100.
        /// </summary>
        public static string app_BinaryInstructions {
            get {
                return ResourceManager.GetString("app_BinaryInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing a box.
        /// </summary>
        public static string app_DrawingABox {
            get {
                return ResourceManager.GetString("app_DrawingABox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing a circle.
        /// </summary>
        public static string app_DrawingACircle {
            get {
                return ResourceManager.GetString("app_DrawingACircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing a line.
        /// </summary>
        public static string app_DrawingALine {
            get {
                return ResourceManager.GetString("app_DrawingALine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a shape to draw. Should be Circle, Box, or Line.
        /// </summary>
        public static string app_DrawInstructions {
            get {
                return ResourceManager.GetString("app_DrawInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a phrase to be transformed, include numbers, and letters of both upper and lower case..
        /// </summary>
        public static string app_Instructions {
            get {
                return ResourceManager.GetString("app_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid shape, please use Circle, Box, or Line.
        /// </summary>
        public static string app_InvalidShapeExceptionMessage {
            get {
                return ResourceManager.GetString("app_InvalidShapeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now try an invalid shape like Oval, Square, or Tree.
        /// </summary>
        public static string app_TryAnInvalidString {
            get {
                return ResourceManager.GetString("app_TryAnInvalidString", resourceCulture);
            }
        }
    }
}
